### ISSUE TITLE
Improper WebView resolution

### ISSUE THREAD

**Issue by Hanfrey** [Devecstatic/SSMP#3]
Hi,

first: great project!

I tested a little bit with your example project. I wasn't able to change the size of the UIViewController, it sticks to the 9xx when I use the second screen.  The UIWindow Object has my 1920px from the TV. I tried to set the Freemform Size to this, but still stays small. 

I added a WKWebView to the UIViewController, but it seems that the clicks are not recognized. Any Idea to get this fixed?

Thanks in advance!

**Comment by EthanLipnik** [comment]
Thanks for trying it! Have you tried changing the AutoLayout?

**Comment by Hanfrey** [comment]
I made a new UIViewController

```
import UIKit
import WebKit

class WebController: UIViewController,WKNavigationDelegate {
    var webView: WKWebView!
    
    override func viewDidLoad() {
        super.viewDidLoad()
        
        let label = UILabel(frame:CGRect(x: 0, y: 0, width: 400, height: 100))
        let second =  UIScreen.screens[1]
        let secondWindow = UIWindow(frame: second.bounds)
        webView = WKWebView(frame: secondWindow.frame)
        webView.navigationDelegate = self

        self.view = webView
        label.text =  "\(secondWindow.frame.width) \(self.view.frame.width)  \(self.webView.frame.width)"

        var url = URL(string: "https://bestfirms.com/what-is-my-screen-resolution/")!
        webView.load(URLRequest(url: url))
        webView.allowsBackForwardNavigationGestures = true
        view.addSubview(label)
        
 
        
    }
}

```
But it looks like the Website I open just does not correct show the size. Other Websites looking not like 414x896. But im still not able to have a click regonized in the WKWebview.

**Comment by EthanLipnik** [comment]
Webview gestures aren't available yet, but it should be ready this week hopefully.

Also, you don't need to do that code to get the window. Doing `SSMPApp.default.secondWindow` should give you the window.

As for the resolution, I'm not sure what's going on here. I'll create some experiments with WebViews and try to find a solution. Thanks for bringing this to my attention!

**Comment by EthanLipnik** [comment]
I found the resolution error. It seems to be something with either external monitors or `WebKit` that I have no control over. Based on my tests, it looks like the websites are rendered at the correct resolution, so my guess is it's reporting the wrong resolution.

I'm currently working on adding more `WebView` support, including changing the user agent to the Mac one for desktop sites.

**Comment by Hanfrey** [comment]
Yes, I thought the same. Renders correct, but reports wrong.
Thanks for having a look and im looking forward to test the stuff :).

**Comment by EthanLipnik** [comment]
So I just updated it to allow for scrolling on web views. I can't figure out interaction though, going to do some more work on it.

**Comment by Hanfrey** [comment]
Scrolling did work for me before, with two fingers up and down, at least if you dont at it as subview.

**Comment by EthanLipnik** [comment]
Well now its officially supported. I'm going to close this issue as we found it and it's being addressed. If you'd like to talk to me more, just email me at ethanlipnik@gmail.com
